version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Root2008@Password123!
      - MSSQL_PID=Developer
    ports:
      - "14333:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: