# application-local.yml
spring:
  datasource:
    url: jdbc:sqlserver://localhost:14333;databaseName=study_platform;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Root2008@Password123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true


  flyway:
    enabled: true
    schemas:  flyway_schema
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:db/migration/modulith
      - classpath:db/migration/user

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST



  integration:
    payment:
      mode: mock
      mock:
        failure-rate: 20  # 20% de falhas para teste
    inventory:
      mode: mock
    notification:
      mode: mock

    #### Events Config ######
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
      completion:
        enabled: true
      republish-outstanding-events-on-restart: true
    modules:
      # Permite dependências explícitas entre módulos
      detect-dependencies: true
      # Mostra o módulo no log
      log-violations: true

logging:
  level:
    root: INFO
    br.com.rafaellbarros.user: DEBUG
    org.springframework.cache: DEBUG